### ISSUE TITLE
how to configure .env

### ISSUE THREAD

**Issue by Reapor-Yurnero** [searx/searx-docker#11]
Hi I'm new here and trying to deploy a searx service on my own vps. Do you have any sample configuration? Thank you!

**Comment by dalf** [comment]
There is [an sample ](https://github.com/searx/searx-docker/blob/master/.env) in the git repository.
* Modify SEARX_HOSTNAME.
* Comment SEARX_PROTOCOL and SEARX_TLS
* Modify LETSENCRYPT_EMAIL
* Set LETSENCRYPT_AGREE to true
* Modify MORTY_KEY (see comment)
* Modify FILTRON_PASSWORD (see comment)

Then follow https://github.com/searx/searx-docker#how-to-use-it (adapt according to your need).

**Comment by Reapor-Yurnero** [comment]
> There is [an sample ](https://github.com/searx/searx-docker/blob/master/.env) in the git repository.
> 
> * Modify SEARX_HOSTNAME.
> * Comment SEARX_PROTOCOL and SEARX_TLS
> * Modify LETSENCRYPT_EMAIL
> * Set LETSENCRYPT_AGREE to true
> * Modify MORTY_KEY (see comment)
> * Modify FILTRON_PASSWORD (see comment)
> 
> Then follow https://github.com/searx/searx-docker#how-to-use-it (adapt according to your need).

Thanks for your prompt reply but I do see these info. My question is how should I modify those paramaters if i want to deploy it on my own VPS.

- what does hostname represent here? is it the address client should access? in my case, should it be the public ip address of my vps?
- what is the LETSENCRYPT_EMAIL used for? should it be my real email address which i want to use on internet?
- how is FILTRON_PASSWORD used? I checked FILTRON repo and didn't get why we need an account for it here.

**Comment by dalf** [comment]
Will you provide access to your searx instance using a DNS name ? or an IP address ?

.env and [Caddyfile](https://github.com/searx/searx-docker/blob/master/Caddyfile) are configure to provide an HTTPS access using a DNS name. Caddy will create a HTTPS certificate from Let's encrypt.

Let's encrypt requires an email to sent some information, no spam (example: domain name about to expire). So that's the purpose of LETSENCRYPT_EMAIL

About Filtron password : the purpose is to hide the statistics (at the relative URL:  /filtron/rules ), so a bot's creator won't be able to see how to bypass filtron. 
If you don't care, you can remove ```basicauth /filtron {$FILTRON_USER} {$FILTRON_PASSWORD}``` from Caddyfile.

**Comment by dalf** [comment]
I close the issue, feel free to reopen.
