### ISSUE TITLE
Can you make some instructions for windows users?

### ISSUE THREAD

**Issue by masterofobzene** [searx/searx-docker#110]
I mean almost none of the start page readme works under windows. I'm lost.

**Comment by masterofobzene** [comment]
I keep reading and nothing makes sense. Can anybody please do some explanation? 
Stop asuming that everybody knows how to use docker and everybody uses unix derived OS's.

**Comment by masterofobzene** [comment]
![imagen](https://user-images.githubusercontent.com/94469116/152033247-a9884a5f-a59b-4310-beba-438a850f6281.png)

**Comment by unixfox** [comment]
We unfortunately don't really support Windows on searx-docker. I think you should try to run searx-docker under WSL instead.

**Comment by masterofobzene** [comment]
I think the official docker image should point out that this is linux and advanced users only.

![imagen](https://user-images.githubusercontent.com/94469116/152034412-d31c6948-0754-474a-bd82-bf21868eb47e.png)

**Comment by unixfox** [comment]
searx-docker is for Linux only because it includes stuff that only works with Linux, like systemd and some bash scripts.

If you have docker installed in local on Windows and `docker` is working in the command line then you can quickly spin up Searx using this command:
```
docker run --rm -d -p 8080:8080 -e BASE_URL=http://localhost:8080/ searx/searx
```

SearX will then be accessible from http://localhost:8080

--------

Closing this issue as there is no plan to support Windows in searx-docker.

**Comment by masterofobzene** [comment]
Thanks for your explanation, makes sense. I was just a little pissed off because nobody stated that its linux only and I lost time. 
One could see that those commands are from linux but the barriers between windows and linux are getting blurry now and sometimes they can be run (like bash scripts, now that a linux kernel can be used in windows)

**Comment by unixfox** [comment]
You can't run bash scripts from Windows directly, you need either Linux in a VM or WSL (Windows Subsystem for Linux) and if you are using WSL then you aren't using Windows but Linux.

I'm sorry, but your point doesn't make a lot of sense.

Moreover, usually people hosting services like searx or nextcloud in a server are very frequently doing that on Linux, it's very rare to see people doing that on Windows. That's why in the open source world, you will most of the time encounter very few tutorials for Windows.

Especially in the privacy "world" too because Windows is a nightmare for privacy.

My final word is that in the open source world, the developers officially support the operating system that they use, very few developers will go out of their way to support the operating systems that they don't personally use. In the SearX team nobody uses Windows, so it made sense to officially support only Linux.

Usually, the Windows support in an open source project comes from some external contributors that wanted to have this specific project on Windows and they took their time to make the project working on Windows. You can't take for granted that a developer of a specific project HAS to support Windows or even MacOS or FreeBSD.

If you want a project to support Windows then the best way is to do it yourself and publish the changes that you did for having the project working on Windows. That's the beauty of open source 😃.
