### ISSUE TITLE
Changing caddy port in docker-compose.yaml not working

### ISSUE THREAD

**Issue by dannykorpan** [searx/searx-docker#12]
Hi,

I've changed the caddy ports to other ports than the default in the docker-compose.yaml,

>     ports:
>       - 8086:80
>       - 44386:443

but after starting the searx-instance, i've get the error

> caddy            | 2019/10/31 09:15:00 Listen: listen tcp :443: bind: address already in use

**Comment by dalf** [comment]
Remove ```network_mode: host```: https://github.com/searx/searx-docker/blob/e4e3aa48f448c79873897fa216dd78cda9a43011/docker-compose.yaml#L11

**Comment by dalf** [comment]
I close the issue, feel free to reopen.

**Comment by notDavid** [comment]
@dalf Hi there, question, perhaps you could point me in the right direction :)

After changing the 2 ports (because 80 and 443 are already in use on my vps) and removing `network_mode: host` i get the error:

```
Creating network "searx-docker_default" with the default driver
ERROR: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
```

Any ideas how i could fix this? Specifying a specific interface or ip address perhaps?
(my docker installation/other images work fine.)

```
ports:
      - 50080:80
      - 50443:443
#network_mode: host
```

Docker version 19.03.5
docker-compose version 1.25.3
Ubuntu 18.04.3

**Comment by notDavid** [comment]
@dalf Nevermind, this seems to be an issue related to [an active openvpn client/interface...](https://stackoverflow.com/a/56136591)
