### ISSUE TITLE
start.sh issue

### ISSUE THREAD

**Issue by pkntl** [searx/searx-docker#14]
I'm setting up searx-docker on an Odroid C2 running DietPi. When I run start.sh I get the following errors:
``` 
use docker-compose.yaml
Stopping filtron       ... done
Stopping searx-checker ... done
Stopping morty         ... done
Stopping searx         ... done
Removing caddy         ... done
Removing filtron       ... done
Removing searx-checker ... done
Removing morty         ... done
Removing searx         ... done
Removing network searx-docker_searx
Removing volume searx-docker_searx-checker
No stopped containers
Creating network "searx-docker_searx" with the default driver
Creating volume "searx-docker_searx-checker" with default driver
Creating morty         ... done
Creating searx         ... done
Creating searx-checker ... done
Creating caddy         ... done
Creating filtron       ... done
Attaching to caddy, morty, searx-checker, filtron, searx
caddy            | standard_init_linux.go:211: exec user process caused "exec format error"
filtron          | standard_init_linux.go:211: exec user process caused "exec format error"
caddy exited with code 1
morty            | WARNING: no logs are available with the 'none' log driver
searx            | standard_init_linux.go:211: exec user process caused "exec format error"
searx-checker    | standard_init_linux.go:211: exec user process caused "exec format error"
searx-checker exited with code 1
searx exited with code 1
morty exited with code 1
```

Any ideas what would be causing the `standard_init_linux.go:211: exec user process caused "exec format error"` error? Could this be a distro issue?

**Comment by Jyawhurh** [comment]
I found this fileand this json .. I hope it helps you solve the
problem. In any case, contact me and keep me informed because as far
as I can I try to do my best to carry out the project :)

This is RSS
<rss version="2.0"><channel><title>Searx search: I'm setting up
searx-docker on an Odroid C2 running DietPi. When I run start.sh I get
the following errors:use docker-compose.yamlStopping filtron       ...
doneStopping searx-checker ... doneStopping morty         ...
doneStopping searx         ... doneRemoving caddy         ...
doneRemoving filtron       ... doneRemoving searx-checker ...
doneRemoving morty         ... doneRemoving searx         ...
doneRemoving network searx-docker_searxRemoving volume
searx-docker_searx-checkerNo stopped containersCreating network
"searx-docker_searx" with the default driverCreating volume
"searx-docker_searx-checker" with default driverCreating morty
... doneCreating searx         ... doneCreating searx-checker ...
doneCreating caddy         ... doneCreating filtron       ...
doneAttaching to caddy, morty, searx-checker, filtron, searxcaddy
      | standard_init_linux.go:211: exec user process caused "exec
format error"filtron          | standard_init_linux.go:211: exec user
process caused "exec format error"caddy exited with code 1morty
    | WARNING: no logs are available with the 'none' log driversearx
         | standard_init_linux.go:211: exec user process caused "exec
format error"searx-checker    | standard_init_linux.go:211: exec user
process caused "exec format error"searx-checker exited with code
1searx exited with code 1morty exited with code 1Any ideas what would
be causing the standard_init_linux.go:211: exec user process caused
"exec format error" error? Could this be a distro
issue?</title><link>https://searx.me/?q=I'm setting up searx-docker on
an Odroid C2 running DietPi. When I run start.sh I get the following
errors:use docker-compose.yamlStopping filtron       ... doneStopping
searx-checker ... doneStopping morty         ... doneStopping searx
     ... doneRemoving caddy         ... doneRemoving filtron       ...
doneRemoving searx-checker ... doneRemoving morty         ...
doneRemoving searx         ... doneRemoving network
searx-docker_searxRemoving volume searx-docker_searx-checkerNo stopped
containersCreating network "searx-docker_searx" with the default
driverCreating volume "searx-docker_searx-checker" with default
driverCreating morty         ... doneCreating searx         ...
doneCreating searx-checker ... doneCreating caddy         ...
doneCreating filtron       ... doneAttaching to caddy, morty,
searx-checker, filtron, searxcaddy            |
standard_init_linux.go:211: exec user process caused "exec format
error"filtron          | standard_init_linux.go:211: exec user process
caused "exec format error"caddy exited with code 1morty            |
WARNING: no logs are available with the 'none' log driversearx
   | standard_init_linux.go:211: exec user process caused "exec format
error"searx-checker    | standard_init_linux.go:211: exec user process
caused "exec format error"searx-checker exited with code 1searx exited
with code 1morty exited with code 1Any ideas what would be causing the
standard_init_linux.go:211: exec user process caused "exec format
error" error? Could this be a distro issue?</link><description>Search
results for "I'm setting up searx-docker on an Odroid C2 running
DietPi. When I run start.sh I get the following errors:use
docker-compose.yamlStopping filtron       ... doneStopping
searx-checker ... doneStopping morty         ... doneStopping searx
     ... doneRemoving caddy         ... doneRemoving filtron       ...
doneRemoving searx-checker ... doneRemoving morty         ...
doneRemoving searx         ... doneRemoving network
searx-docker_searxRemoving volume searx-docker_searx-checkerNo stopped
containersCreating network "searx-docker_searx" with the default
driverCreating volume "searx-docker_searx-checker" with default
driverCreating morty         ... doneCreating searx         ...
doneCreating searx-checker ... doneCreating caddy         ...
doneCreating filtron       ... doneAttaching to caddy, morty,
searx-checker, filtron, searxcaddy            |
standard_init_linux.go:211: exec user process caused "exec format
error"filtron          | standard_init_linux.go:211: exec user process
caused "exec format error"caddy exited with code 1morty            |
WARNING: no logs are available with the 'none' log driversearx
   | standard_init_linux.go:211: exec user process caused "exec format
error"searx-checker    | standard_init_linux.go:211: exec user process
caused "exec format error"searx-checker exited with code 1searx exited
with code 1morty exited with code 1Any ideas what would be causing the
standard_init_linux.go:211: exec user process caused "exec format
error" error? Could this be a distro issue?" -
searx</description><opensearch:totalResults>0</opensearch:totalResults><opensearch:startIndex>1</opensearch:startIndex><opensearch:itemsPerPage>0</opensearch:itemsPerPage><atom:link
rel="search" type="application/opensearchdescription+xml"
href="https://searx.me/opensearch.xml"/><opensearch:Query
role="request" searchTerms="I'm setting up searx-docker on an Odroid
C2 running DietPi. When I run start.sh I get the following errors:use
docker-compose.yamlStopping filtron       ... doneStopping
searx-checker ... doneStopping morty         ... doneStopping searx
     ... doneRemoving caddy         ... doneRemoving filtron       ...
doneRemoving searx-checker ... doneRemoving morty         ...
doneRemoving searx         ... doneRemoving network
searx-docker_searxRemoving volume searx-docker_searx-checkerNo stopped
containersCreating network "searx-docker_searx" with the default
driverCreating volume "searx-docker_searx-checker" with default
driverCreating morty         ... doneCreating searx         ...
doneCreating searx-checker ... doneCreating caddy         ...
doneCreating filtron       ... doneAttaching to caddy, morty,
searx-checker, filtron, searxcaddy            |
standard_init_linux.go:211: exec user process caused "exec format
error"filtron          | standard_init_linux.go:211: exec user process
caused "exec format error"caddy exited with code 1morty            |
WARNING: no logs are available with the 'none' log driversearx
   | standard_init_linux.go:211: exec user process caused "exec format
error"searx-checker    | standard_init_linux.go:211: exec user process
caused "exec format error"searx-checker exited with code 1searx exited
with code 1morty exited with code 1Any ideas what would be causing the
standard_init_linux.go:211: exec user process caused "exec format
error" error? Could this be a distro issue?"
startPage="1"/><item><title>[SOLVED] Docker not starting automatically
on v6.19.7 | Odroid C2
...</title><link>https://dietpi.com/phpbb/viewtopic.php?f=11&t=5320</link><description>Docker
doesn't start automatically on this version (fresh install), getting
this error on docker commands: Cannot connect to the Docker daemon at
unix:///var/run/ docker.sock. Is the docker daemon running. When I run
this command: /usr/bin/ dockerd -H unix:// & ( found in
/lib/systemd/system/docker.service
)</description></item><item><title>[SOLVED] Startup script not running
after hard reset -
ODROID</title><link>https://forum.odroid.com/viewtopic.php?t=16221</link><description>When
I send the command to reboot my XU-3, the script runs fine. ... I'm
pretty sure). ... If you're using Ubuntu 15.04 it's very likely
rc.local is not loaded, since ... rc.local files (unless you have a
systemd configuration for that ;) ) ... I can check later, but would
that be the issue since the script does run after a
...</description></item><item><title>docker-libresonic/jetty-runner at
master · linuxserver-archive/docker
...</title><link>https://github.com/linuxserver-archive/docker-libresonic/blob/master/prebuilds/jetty-runner</link><description>PLEASE
USE AIRSONIC `linuxserver/airsonic` - linuxserver-archive/docker-
libresonic. ... docker-libresonic/prebuilds/jetty-runner. Find file
Copy path. Fetching
...</description></item><item><title>docker-libresonic-armhf/jetty-runner
at master · linuxserver-archive
...</title><link>https://github.com/linuxserver-archive/docker-libresonic-armhf/blob/master/prebuilds/jetty-runner</link><description>GitHub
is home to over 40 million developers working together to host and
review code, manage projects, and build software together. Sign up.
Branch: master.</description></item></channel></rss>


2019-11-19 14:51 GMT+01:00, desigi <notifications@github.com>:

**Comment by pkntl** [comment]
Unfortunately none of those links were very helpful.

**Comment by dalf** [comment]
The current Docker image is only published for the amd64 architecture, not for the arm64 architecture (the one used by Odroid C2).

travis (the current CI) seems to support multiple architecture build :
https://docs.travis-ci.com/user/multi-cpu-architectures/#using-docker-in-multiple-cpu-architecture-based-builds-within-lxd-containers

**Comment by pkntl** [comment]
Ok thank you. I actually got it working without using Docker. Good solution for me until arm64 is supported.
