### ISSUE TITLE
installing searx with https on a different port

### ISSUE THREAD

**Issue by hakova** [searx/searx-docker#39]
Hi,

I apologize in advance if this is a silly question, but what I am trying to do is installing searx container to be reachable from outside world by https from a non-conventional port. To accomplish this, I copied the docker-compose.yaml file to docker-compose-extend.yaml file and edited the caddy ports section to read as follows:
- 25000:80
- 25001:443
Host machine firewall was set to allow access to the ports 25000 and 25001 via tcp. The edge router was also set to forward ports 80 and 443 to 25000 and 25001 respectively on the host machine.
Then I tested these settings by running start.sh which reported that Letsencrypt could not access the ports for certification.

What am I missing?

Thanks for the pointers in advance!

**Comment by jeremiah-k** [comment]
Have you had any luck? I have been trying to figure this out too.

**Comment by hakova** [comment]
Nope, not with this container/package. I compromised with installing another searx container (wonderfall/searx) which allows you to switch ports as described above and very easily, but lacks the SSL layer. I don't expose that port to internet and make it only available within my LAN. This was the solution I settled with, I hope it helps.

**Comment by dalf** [comment]
Since the commit bdf5619765ac9457eb0bb4107dba2db10eddd724 this solution should work:
* edit Caddyfile
* after https://github.com/searx/searx-docker/blob/bdf5619765ac9457eb0bb4107dba2db10eddd724/Caddyfile#L2 add :
```
http_port 25000
https_port 25001
```

See https://caddyserver.com/docs/caddyfile/options

---

No need to modify docker-compose.yml , because of https://github.com/searx/searx-docker/blob/bdf5619765ac9457eb0bb4107dba2db10eddd724/docker-compose.yaml#L8 (see https://github.com/searx/searx-docker/pull/26 )

**Comment by hakova** [comment]
Thank you @dalf. This is now resolved.
